image: python:3.11.8-bookworm

pipelines:
  branches:
    new_structure:
      - step:
          name: Copy last version to server
          script:
            - rm -f bitbucket-pipelines.yml package.json package-lock.json .env .env.example .gitignore scr/api/v1/endpoints/test.py deploy.sh
            - rm -fR templates/
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $SCANNSPLIT_APP_TEST_SRV_USER
                SERVER: $SCANNSPLIT_APP_TEST_SRV_HOST
                REMOTE_PATH: '/app/api'
                LOCAL_PATH: './*'
      - step:
          name: run deploy.sh script
          script:
            - pipe: atlassian/ssh-run:0.8.0
              variables:
                SSH_USER: $SCANNSPLIT_APP_TEST_SRV_USER
                SERVER: $SCANNSPLIT_APP_TEST_SRV_HOST
                COMMAND: cd '/app/api' && /bin/bash deploy.sh 
    master:
      - step:
          name: Copy last version to server
          script:
            - rm -f bitbucket-pipelines.yml package.json package-lock.json .env
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $SCANNSPLIT_APP_TEST_SRV_USER
                SERVER: $SCANNSPLIT_APP_TEST_SRV_HOST
                REMOTE_PATH: '/app'
                LOCAL_PATH: './*'
      - step:
          name: run deploy.sh script
          script:
            - pipe: atlassian/ssh-run:0.8.0
              variables:
                SSH_USER: $SCANNSPLIT_APP_TEST_SRV_USER
                SERVER: $SCANNSPLIT_APP_TEST_SRV_HOST
                COMMAND: cd /app && chmod 755 deploy.sh && /bin/bash deploy.sh && chmod 555 deploy.sh